# Generated by Django 3.0.6 on 2020-05-20 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taikoblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
